### PR TITLE
chore: document crd upgrades

### PR DESCRIPTION
**Pull request by toddbaert**
Adds docs for upgrading CRDs via helm.

Fixes: https://github.com/open-feature/open-feature-operator/issues/354

### CODE REVIEW

**Review by Kavindu-Dodan — APPROVED** [review]

**Review by thisthat — APPROVED** [review]
LGTM

**Review by mowies — COMMENTED** [review]
some general things that may help with UX:
- For docs I think it always makes sense to use the full name flags and not shorthand, so that command are easier to read for users (i.e. `-i` -> `--install`)
- you can call `helm template` also on remote charts then you could skip the download step

**Comment by toddbaert** [comment]
> * For docs I think it always makes sense to use the full name flags and not shorthand, so that command are easier to read for users (i.e. `-i` -> `--install`)

I actually strongly agree with this. This is usually my policy in scripts too, to keep things readable. I will make this change.

> * you can call `helm template` also on remote charts then you could skip the download step

TIL! I will update to this, since it's simpler I think.

**Comment by toddbaert** [comment]
@mowies I have done the needful, please have a quick look. Thanks for those suggestions.

**Comment by toddbaert** [comment]
@mowies I'm going to merge this since I _think_ I've addressed your concerns and I'd like to have this documented for our next release. If that's not true, please comment and I will resolve with a new PR.

**Pull request merged**
