### PR TITLE
chore: add additional Kubernetes files

### PR DESCRIPTION
**Pull request by beeme1mr**
## Overview

This pr basically extends awareness if the files renovate bot should watch. This should help keep the RBAC container up-to-date. It also extends the renovate bot configuration to add a `renovate` label.

An example of why the RBAC issue is important can be found in [this PR](https://github.com/open-feature/open-feature-operator/pull/243). I had to manually search for an update the version number.

Signed-off-by: Michael Beemer <beeme1mr@users.noreply.github.com>

### CODE REVIEW

**Comment by AlexsJones** [comment]
What does this do @beeme1mr  ?

**Comment by toddbaert** [comment]
> What does this do @beeme1mr ?

I'm not sure either :sweat_smile: . @beeme1mr could you give a quick TDLR?

**Comment by beeme1mr** [comment]
Here's an example where I had to manually update file missed by Renovate.

https://github.com/open-feature/open-feature-operator/pull/243

**Review by toddbaert — APPROVED** [review]
I understand now, thanks a lot @beeme1mr

**Comment by toddbaert** [comment]
@beeme1mr can this be updated and merged?

**Comment by beeme1mr** [comment]
Yes, it just needs one more approval.

**Review by skyerus — APPROVED** [review]

**Pull request merged**
